### ISSUE TITLE
DRENet model on DOTA , NWPU VHR , DIOR  datasets  results ?

### ISSUE THREAD

**Issue by TerrafYassin** [WindVChen/DRENet#1]
please can i use your model on DOTA , NWPU VHR , DIOR , did you test it on this datasets , can give a good resuls ?

**Comment by WindVChen** [comment]
@TerrafYassin Sorry for replying late. Since our method is mainly for the ship detection task under medium resolution remote sensing image, we didn't test our method on these datasets which are at a high resolution. 

If you want to try DRENet on these high-resolution datasets, the pretrained method provided currently is not suitable to directly apply, as it is trained on [LEVIR-Ship](https://github.com/WindVChen/LEVIR-Ship). You can follow the "Run Details" in the README.md of this repository and train the model on the other datasets from scratch.
